### ISSUE TITLE
Conversion Error upon length quantizing

### ISSUE THREAD

**Issue by johncwok** [JuliaMusic/MusicManipulations.jl#39]
Upon trying to quantize the notes of the following file with the grid ```[0,0.383,0.73,1]```:

[Piano - OP002.zip](https://github.com/JuliaMusic/MusicManipulations.jl/files/3762332/Piano.-.OP002.zip)

I encountered the following error :
```Julia
ERROR: LoadError: InexactError: Int64(700.8)
```
It is due to this line of code (line 118 of ```quantize.jl```) : 
```Julia
final_dur = Int(grid[best]*tpq)
```
Which for some reason refuses to convert.
I have tried couple of things that didn't work, and for now my solution is to pass ```false``` for the argument quantizing length.

**Comment by Datseris** [comment]
You just have to change 
```
final_dur = Int(grid[best]*tpq)
```
to
```
final_dur = round(Int, grid[best]*tpq))
```
please do a PR that does this and add a minor test for it :)

**Comment by johncwok** [comment]
Already tried that, doesn't work. Conversion seems to be a common issue in Julia for some reason..

**Comment by Datseris** [comment]
Are you **really sure** that `final_dur = round(Int, grid[best]*tpq)` doesn't work? Because you might be getting an error from a different line of the source code.

When writing this function I have always assumed that `grid * tpq` will always result in integers, an assumption I now see was wrong. Replacing these products with their `round(int, ...)` version should fix all problems.

Anyway, this should be very easy to fix, I'll do it soon and add a test case that uses your midi file.

---

p.s.: I don't agree with your statement that conversion is a common problem!
